export const flag = [
    '<i class="em em-flag-eu" aria-role="presentation" aria-label="European Union Flag"></i>',
    '<i class="em em-flag-ca" aria-role="presentation" aria-label="Canada Flag"></i>',
    '<i class="em em-flag-hk" aria-role="presentation" aria-label="Hong Kong SAR China Flag"></i>',
    '<i class="em em-flag-is" aria-role="presentation" aria-label="Iceland Flag"></i>',
    '<i class="em em-flag-ph" aria-role="presentation" aria-label="Philippines Flag"></i>',
    '<i class="em em-flag-dk" aria-role="presentation" aria-label="Denmark Flag"></i>',
    '<i class="em em-flag-hu" aria-role="presentation" aria-label="Hungary Flag"></i>',
    '<i class="em em-flag-cz" aria-role="presentation" aria-label="Czechia Flag"></i>',
    '<i class="em em-flag-au" aria-role="presentation" aria-label="Australia Flag"></i>',
    '<i class="em em-flag-ro" aria-role="presentation" aria-label="Romania Flag"></i>',
    '<i class="em em-flag-se" aria-role="presentation" aria-label="Sweden Flag"></i>',
    '<i class="em em-flag-id" aria-role="presentation" aria-label="Indonesia Flag"></i>',
    '<i class="em em-flag-in" aria-role="presentation" aria-label="India Flag"></i>',
    '<i class="em em-flag-br" aria-role="presentation" aria-label="Brazil Flag"></i>',
    '<i class="em em-flag-rs" aria-role="presentation" aria-label="Serbia Flag"></i>',
    '<i class="em em-flag-hr" aria-role="presentation" aria-label="Croatia Flag"></i>',
    '<i class="em em-jp" aria-role="presentation" aria-label="Japan Flag"></i>',
    '<i class="em em-flag-th" aria-role="presentation" aria-label="Thailand Flag"></i>',
    '<i class="em em-flag-ch" aria-role="presentation" aria-label="Switzerland Flag"></i>',
    '<i class="em em-flag-sg" aria-role="presentation" aria-label="Singapore Flag"></i>',
    '<i class="em em-flag-pl" aria-role="presentation" aria-label="Poland Flag"></i>',
    '<i class="em em-flag-bg" aria-role="presentation" aria-label="Bulgaria Flag"></i>',
    '<i class="em em-flag-tr" aria-role="presentation" aria-label="Turkey Flag"></i>',
    '<i class="em em-cn" aria-role="presentation" aria-label="China Flag"></i>',
    '<i class="em em-flag-no" aria-role="presentation" aria-label="Norway Flag"></i>',
    '<i class="em em-flag-nz" aria-role="presentation" aria-label="New Zealand Flag"></i>',
    '<i class="em em-flag-za" aria-role="presentation" aria-label="South Africa Flag"></i>',
    '<i class="em em-flag-um" aria-role="presentation" aria-label="U.S. Flag"></i>',
    '<i class="em em-flag-mx" aria-role="presentation" aria-label="Mexico Flag"></i>',
    '<i class="em em-flag-il" aria-role="presentation" aria-label="Israel Flag"></i>',
    '<i class="em em-gb" aria-role="presentation" aria-label="United Kingdom Flag"></i>',
    '<i class="em em-kr" aria-role="presentation" aria-label="South Korea Flag"></i>',
    '<i class="em em-flag-my" aria-role="presentation" aria-label="Malaysia Flag"></i>'
]
